const codes = [
  'AF',
  'AL',
  'DZ',
  'AS',
  'AD',
  'AO',
  'AI',
  'AQ',
  'AG',
  'AR',
  'AM',
  'AW',
  'AU',
  'AT',
  'AZ',
  'BS',
  'BH',
  'BD',
  'BB',
  'BY',
  'BE',
  'BZ',
  'BJ',
  'BM',
  'BT',
  'BO',
  'BQ',
  'BA',
  'BW',
  'BV',
  'BR',
  'IO',
  'VG',
  'BN',
  'BG',
  'BF',
  'BI',
  'CV',
  'KH',
  'CM',
  'CA',
  'KY',
  'CF',
  'TD',
  'CL',
  'CN',
  'HK',
  'MO',
  'CX',
  'CC',
  'CO',
  'KM',
  'CG',
  'CK',
  'CR',
  'HR',
  'CU',
  'CW',
  'CY',
  'CZ',
  'CI',
  'KP',
  'CD',
  'DK',
  'DJ',
  'DM',
  'DO',
  'EC',
  'EG',
  'SV',
  'GQ',
  'ER',
  'EE',
  'SZ',
  'ET',
  'FK',
  'FO',
  'FJ',
  'FI',
  'FR',
  'GF',
  'PF',
  'TF',
  'GA',
  'GM',
  'GE',
  'DE',
  'GH',
  'GI',
  'GR',
  'GL',
  'GD',
  'GP',
  'GU',
  'GT',
  'GG',
  'GN',
  'GW',
  'GY',
  'HT',
  'HM',
  'VA',
  'HN',
  'HU',
  'IS',
  'IN',
  'ID',
  'IR',
  'IQ',
  'IE',
  'IM',
  'IL',
  'IT',
  'JM',
  'JP',
  'JE',
  'JO',
  'KZ',
  'KE',
  'KI',
  'KW',
  'KG',
  'LA',
  'LV',
  'LB',
  'LS',
  'LR',
  'LY',
  'LI',
  'LT',
  'LU',
  'MG',
  'MW',
  'MY',
  'MV',
  'ML',
  'MT',
  'MH',
  'MQ',
  'MR',
  'MU',
  'YT',
  'MX',
  'FM',
  'MC',
  'MN',
  'ME',
  'MS',
  'MA',
  'MZ',
  'MM',
  'NA',
  'NR',
  'NP',
  'NL',
  'NC',
  'NZ',
  'NI',
  'NE',
  'NG',
  'NU',
  'NF',
  'MP',
  'NO',
  'OM',
  'PK',
  'PW',
  'PA',
  'PG',
  'PY',
  'PE',
  'PH',
  'PN',
  'PL',
  'PT',
  'PR',
  'QA',
  'KR',
  'MD',
  'RO',
  'RU',
  'RW',
  'RE',
  'BL',
  'SH',
  'KN',
  'LC',
  'MF',
  'PM',
  'VC',
  'WS',
  'SM',
  'ST',
  'saudi',
  'SA',
  'SN',
  'RS',
  'SC',
  'SL',
  'SG',
  'SX',
  'SK',
  'SI',
  'SB',
  'SO',
  'ZA',
  'GS',
  'SS',
  'ES',
  'LK',
  'PS',
  'SD',
  'SR',
  'SJ',
  'SE',
  'CH',
  'SY',
  'TJ',
  'TH',
  'MK',
  'TL',
  'TG',
  'TK',
  'TO',
  'TT',
  'TN',
  'TR',
  'TM',
  'TC',
  'TV',
  'UG',
  'UA',
  'AE',
  'GB',
  'TZ',
  'UM',
  'VI',
  'US',
  'UY',
  'UZ',
  'VU',
  'VE',
  'VN',
  'WF',
  'EH',
  'YE',
  'ZM',
  'ZW',
  'AX',
];

const dial = [
  '93',
  '355',
  '213',
  '1-684',
  '376',
  '244',
  '1-264',
  '672',
  '1-268',
  '54',
  '374',
  '297',
  '61',
  '43',
  '994',
  '1-242',
  '973',
  '880',
  '1-246',
  '375',
  '32',
  '501',
  '229',
  '1-441',
  '975',
  '591',
  '599',
  '387',
  '267',
  '47',
  '55',
  '246',
  '1-284',
  '673',
  '359',
  '226',
  '257',
  '238',
  '855',
  '237',
  '1',
  '1-345',
  '236',
  '235',
  '56',
  '86',
  '852',
  '853',
  '61',
  '61',
  '57',
  '269',
  '242',
  '682',
  '506',
  '385',
  '53',
  '599',
  '357',
  '420',
  '225',
  '850',
  '243',
  '45',
  '253',
  '1-767',
  '1-809,1-829,1-849',
  '593',
  '20',
  '503',
  '240',
  '291',
  '372',
  '268',
  '251',
  '500',
  '298',
  '679',
  '358',
  '33',
  '594',
  '689',
  '262',
  '241',
  '220',
  '995',
  '49',
  '233',
  '350',
  '30',
  '299',
  '1-473',
  '590',
  '1-671',
  '502',
  '44',
  '224',
  '245',
  '592',
  '509',
  '672',
  '39-06',
  '504',
  '36',
  '354',
  '91',
  '62',
  '98',
  '964',
  '353',
  '44',
  '972',
  '39',
  '1-876',
  '81',
  '44',
  '962',
  '7',
  '254',
  '686',
  '965',
  '996',
  '856',
  '371',
  '961',
  '266',
  '231',
  '218',
  '423',
  '370',
  '352',
  '261',
  '265',
  '60',
  '960',
  '223',
  '356',
  '692',
  '596',
  '222',
  '230',
  '262',
  '52',
  '691',
  '377',
  '976',
  '382',
  '1-664',
  '212',
  '258',
  '95',
  '264',
  '674',
  '977',
  '31',
  '687',
  '64',
  '505',
  '227',
  '234',
  '683',
  '672',
  '1-670',
  '47',
  '968',
  '92',
  '680',
  '507',
  '675',
  '595',
  '51',
  '63',
  '870',
  '48',
  '351',
  '1',
  '974',
  '82',
  '373',
  '40',
  '7',
  '250',
  '262',
  '590',
  '290',
  '1-869',
  '1-758',
  '590',
  '508',
  '1-784',
  '685',
  '378',
  '239',
  '',
  '966',
  '221',
  '381',
  '248',
  '232',
  '65',
  '1-721',
  '421',
  '386',
  '677',
  '252',
  '27',
  '500',
  '211',
  '34',
  '94',
  '970',
  '249',
  '597',
  '47',
  '46',
  '41',
  '963',
  '992',
  '66',
  '389',
  '670',
  '228',
  '690',
  '676',
  '1-868',
  '216',
  '90',
  '993',
  '1-649',
  '688',
  '256',
  '380',
  '971',
  '44',
  '255',
  '',
  '1-340',
  '1',
  '598',
  '998',
  '678',
  '58',
  '84',
  '681',
  '212',
  '967',
  '260',
  '263',
  '358',
];
const en = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia (Plurinational State of)',
  'Bonaire, Sint Eustatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'British Virgin Islands',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'China, Hong Kong Special Administrative Region',
  'China, Macao Special Administrative Region',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Cook Islands',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czechia',
  'Côte d\'Ivoire',
  'Democratic People\'s Republic of Korea',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Holy See',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Lao People\'s Democratic Republic',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia (Federated States of)',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of Korea',
  'Republic of Moldova',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Réunion',
  'Saint Barthélemy',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin (French Part)',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Sark',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'State of Palestine',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen Islands',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Tajikistan',
  'Thailand',
  'The former Yugoslav Republic of Macedonia',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom of Great Britain and Northern Ireland',
  'United Republic of Tanzania',
  'United States Minor Outlying Islands',
  'United States Virgin Islands',
  'United States of America',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela (Bolivarian Republic of)',
  'Viet Nam',
  'Wallis and Futuna Islands',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Åland Islands',
];

const fr = [
  'Afghanistan',
  'Albanie',
  'Algérie',
  'Samoa américaines',
  'Andorre',
  'Angola',
  'Anguilla',
  'Antarctique',
  'Antigua-et-Barbuda',
  'Argentine',
  'Arménie',
  'Aruba',
  'Australie',
  'Autriche',
  'Azerbaïdjan',
  'Bahamas',
  'Bahreïn',
  'Bangladesh',
  'Barbade',
  'Bélarus',
  'Belgique',
  'Belize',
  'Bénin',
  'Bermudes',
  'Bhoutan',
  'Bolivie (État plurinational de)',
  'Bonaire, Saint-Eustache et Saba',
  'Bosnie-Herzégovine',
  'Botswana',
  'Île Bouvet',
  'Brésil',
  'Territoire britannique de l\'océan Indien',
  'Îles Vierges britanniques',
  'Brunéi Darussalam',
  'Bulgarie',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodge',
  'Cameroun',
  'Canada',
  'Îles Caïmanes',
  'République centrafricaine',
  'Tchad',
  'Chili',
  'Chine',
  'Chine, région administrative spéciale de Hong Kong',
  'Chine, région administrative spéciale de Macao',
  'Île Christmas',
  'Îles des Cocos (Keeling)',
  'Colombie',
  'Comores',
  'Congo',
  'Îles Cook',
  'Costa Rica',
  'Croatie',
  'Cuba',
  'Curaçao',
  'Chypre',
  'Tchéquie',
  'Côte d\'Ivoire',
  'République populaire démocratique de Corée',
  'République démocratique du Congo',
  'Danemark',
  'Djibouti',
  'Dominique',
  'République dominicaine',
  'Équateur',
  'Égypte',
  'El Salvador',
  'Guinée équatoriale',
  'Érythrée',
  'Estonie',
  'Eswatini',
  'Éthiopie',
  'Îles Falkland (Malvinas)',
  'Îles Féroé',
  'Fidji',
  'Finlande',
  'France',
  'Guyane française',
  'Polynésie française',
  'Terres australes françaises',
  'Gabon',
  'Gambie',
  'Géorgie',
  'Allemagne',
  'Ghana',
  'Gibraltar',
  'Grèce',
  'Groenland',
  'Grenade',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernesey',
  'Guinée',
  'Guinée-Bissau',
  'Guyana',
  'Haïti',
  'Île Heard-et-Îles MacDonald',
  'Saint-Siège',
  'Honduras',
  'Hongrie',
  'Islande',
  'Inde',
  'Indonésie',
  'Iran (République islamique d\')',
  'Iraq',
  'Irlande',
  'Île de Man',
  'Israël',
  'Italie',
  'Jamaïque',
  'Japon',
  'Jersey',
  'Jordanie',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Koweït',
  'Kirghizistan',
  'République démocratique populaire lao',
  'Lettonie',
  'Liban',
  'Lesotho',
  'Libéria',
  'Libye',
  'Liechtenstein',
  'Lituanie',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaisie',
  'Maldives',
  'Mali',
  'Malte',
  'Îles Marshall',
  'Martinique',
  'Mauritanie',
  'Maurice',
  'Mayotte',
  'Mexique',
  'Micronésie (États fédérés de)',
  'Monaco',
  'Mongolie',
  'Monténégro',
  'Montserrat',
  'Maroc',
  'Mozambique',
  'Myanmar',
  'Namibie',
  'Nauru',
  'Népal',
  'Pays-Bas',
  'Nouvelle-Calédonie',
  'Nouvelle-Zélande',
  'Nicaragua',
  'Niger',
  'Nigéria',
  'Nioué',
  'Île Norfolk',
  'Îles Mariannes du Nord',
  'Norvège',
  'Oman',
  'Pakistan',
  'Palaos',
  'Panama',
  'Papouasie-Nouvelle-Guinée',
  'Paraguay',
  'Pérou',
  'Philippines',
  'Pitcairn',
  'Pologne',
  'Portugal',
  'Porto Rico',
  'Qatar',
  'République de Corée',
  'République de Moldova',
  'Roumanie',
  'Fédération de Russie',
  'Rwanda',
  'Réunion',
  'Saint-Barthélemy',
  'Sainte-Hélène',
  'Saint-Kitts-et-Nevis',
  'Sainte-Lucie',
  'Saint-Martin (partie française)',
  'Saint-Pierre-et-Miquelon',
  'Saint-Vincent-et-les Grenadines',
  'Samoa',
  'Saint-Marin',
  'Sao Tomé-et-Principe',
  'Sercq',
  'Arabie saoudite',
  'Sénégal',
  'Serbie',
  'Seychelles',
  'Sierra Leone',
  'Singapour',
  'Saint-Martin (partie néerlandaise)',
  'Slovaquie',
  'Slovénie',
  'Îles Salomon',
  'Somalie',
  'Afrique du Sud',
  'Géorgie du Sud-et-les Îles Sandwich du Sud',
  'Soudan du Sud',
  'Espagne',
  'Sri Lanka',
  'État de Palestine',
  'Soudan',
  'Suriname',
  'Îles Svalbard-et-Jan Mayen',
  'Suède',
  'Suisse',
  'République arabe syrienne',
  'Tadjikistan',
  'Thaïlande',
  'ex-République yougoslave de Macédoine',
  'Timor-Leste',
  'Togo',
  'Tokélaou',
  'Tonga',
  'Trinité-et-Tobago',
  'Tunisie',
  'Turquie',
  'Turkménistan',
  'Îles Turques-et-Caïques',
  'Tuvalu',
  'Ouganda',
  'Ukraine',
  'Émirats arabes unis',
  'Royaume-Uni de Grande-Bretagne et d\'Irlande du Nord',
  'République-Unie de Tanzanie',
  'Îles mineures éloignées des États-Unis',
  'Îles Vierges américaines',
  'États-Unis d\'Amérique',
  'Uruguay',
  'Ouzbékistan',
  'Vanuatu',
  'Venezuela (République bolivarienne du)',
  'Viet Nam',
  'Îles Wallis-et-Futuna',
  'Sahara occidental',
  'Yémen',
  'Zambie',
  'Zimbabwe',
  'Îles d\'Åland',
];

const flags = {"Ascension Island":{"flag":"🇦🇨","name":"Ascension Island","hex":"U+1F1E6 U+1F1E8"},"Andorra":{"flag":"🇦🇩","name":"Andorra","hex":"U+1F1E6 U+1F1E9"},"United Arab Emirates":{"flag":"🇦🇪","name":"United Arab Emirates","hex":"U+1F1E6 U+1F1EA"},"Afghanistan":{"flag":"🇦🇫","name":"Afghanistan","hex":"U+1F1E6 U+1F1EB"},"Antigua & Barbuda":{"flag":"🇦🇬","name":"Antigua & Barbuda","hex":"U+1F1E6 U+1F1EC"},"Anguilla":{"flag":"🇦🇮","name":"Anguilla","hex":"U+1F1E6 U+1F1EE"},"Albania":{"flag":"🇦🇱","name":"Albania","hex":"U+1F1E6 U+1F1F1"},"Armenia":{"flag":"🇦🇲","name":"Armenia","hex":"U+1F1E6 U+1F1F2"},"Angola":{"flag":"🇦🇴","name":"Angola","hex":"U+1F1E6 U+1F1F4"},"Antarctica":{"flag":"🇦🇶","name":"Antarctica","hex":"U+1F1E6 U+1F1F6"},"Argentina":{"flag":"🇦🇷","name":"Argentina","hex":"U+1F1E6 U+1F1F7"},"American Samoa":{"flag":"🇦🇸","name":"American Samoa","hex":"U+1F1E6 U+1F1F8"},"Austria":{"flag":"🇦🇹","name":"Austria","hex":"U+1F1E6 U+1F1F9"},"Australia":{"flag":"🇦🇺","name":"Australia","hex":"U+1F1E6 U+1F1FA"},"Aruba":{"flag":"🇦🇼","name":"Aruba","hex":"U+1F1E6 U+1F1FC"},"Åland Islands":{"flag":"🇦🇽","name":"Åland Islands","hex":"U+1F1E6 U+1F1FD"},"Azerbaijan":{"flag":"🇦🇿","name":"Azerbaijan","hex":"U+1F1E6 U+1F1FF"},"Bosnia & Herzegovina":{"flag":"🇧🇦","name":"Bosnia & Herzegovina","hex":"U+1F1E7 U+1F1E6"},"Barbados":{"flag":"🇧🇧","name":"Barbados","hex":"U+1F1E7 U+1F1E7"},"Bangladesh":{"flag":"🇧🇩","name":"Bangladesh","hex":"U+1F1E7 U+1F1E9"},"Belgium":{"flag":"🇧🇪","name":"Belgium","hex":"U+1F1E7 U+1F1EA"},"Burkina Faso":{"flag":"🇧🇫","name":"Burkina Faso","hex":"U+1F1E7 U+1F1EB"},"Bulgaria":{"flag":"🇧🇬","name":"Bulgaria","hex":"U+1F1E7 U+1F1EC"},"Bahrain":{"flag":"🇧🇭","name":"Bahrain","hex":"U+1F1E7 U+1F1ED"},"Burundi":{"flag":"🇧🇮","name":"Burundi","hex":"U+1F1E7 U+1F1EE"},"Benin":{"flag":"🇧🇯","name":"Benin","hex":"U+1F1E7 U+1F1EF"},"St. Barthélemy":{"flag":"🇧🇱","name":"St. Barthélemy","hex":"U+1F1E7 U+1F1F1"},"Bermuda":{"flag":"🇧🇲","name":"Bermuda","hex":"U+1F1E7 U+1F1F2"},"Brunei":{"flag":"🇧🇳","name":"Brunei","hex":"U+1F1E7 U+1F1F3"},"Bolivia":{"flag":"🇧🇴","name":"Bolivia","hex":"U+1F1E7 U+1F1F4"},"Caribbean Netherlands":{"flag":"🇧🇶","name":"Caribbean Netherlands","hex":"U+1F1E7 U+1F1F6"},"Brazil":{"flag":"🇧🇷","name":"Brazil","hex":"U+1F1E7 U+1F1F7"},"Bahamas":{"flag":"🇧🇸","name":"Bahamas","hex":"U+1F1E7 U+1F1F8"},"Bhutan":{"flag":"🇧🇹","name":"Bhutan","hex":"U+1F1E7 U+1F1F9"},"Bouvet Island":{"flag":"🇧🇻","name":"Bouvet Island","hex":"U+1F1E7 U+1F1FB"},"Botswana":{"flag":"🇧🇼","name":"Botswana","hex":"U+1F1E7 U+1F1FC"},"Belarus":{"flag":"🇧🇾","name":"Belarus","hex":"U+1F1E7 U+1F1FE"},"Belize":{"flag":"🇧🇿","name":"Belize","hex":"U+1F1E7 U+1F1FF"},"Canada":{"flag":"🇨🇦","name":"Canada","hex":"U+1F1E8 U+1F1E6"},"Cocos (Keeling) Islands":{"flag":"🇨🇨","name":"Cocos (Keeling) Islands","hex":"U+1F1E8 U+1F1E8"},"Congo - Kinshasa":{"flag":"🇨🇩","name":"Congo - Kinshasa","hex":"U+1F1E8 U+1F1E9"},"Central African Republic":{"flag":"🇨🇫","name":"Central African Republic","hex":"U+1F1E8 U+1F1EB"},"Congo - Brazzaville":{"flag":"🇨🇬","name":"Congo - Brazzaville","hex":"U+1F1E8 U+1F1EC"},"Switzerland":{"flag":"🇨🇭","name":"Switzerland","hex":"U+1F1E8 U+1F1ED"},"Côte d'Ivoire":{"flag":"🇨🇮","name":"Côte d'Ivoire","hex":"U+1F1E8 U+1F1EE"},"Cook Islands":{"flag":"🇨🇰","name":"Cook Islands","hex":"U+1F1E8 U+1F1F0"},"Chile":{"flag":"🇨🇱","name":"Chile","hex":"U+1F1E8 U+1F1F1"},"Cameroon":{"flag":"🇨🇲","name":"Cameroon","hex":"U+1F1E8 U+1F1F2"},"China":{"flag":"🇨🇳","name":"China","hex":"U+1F1E8 U+1F1F3"},"Colombia":{"flag":"🇨🇴","name":"Colombia","hex":"U+1F1E8 U+1F1F4"},"Clipperton Island":{"flag":"🇨🇵","name":"Clipperton Island","hex":"U+1F1E8 U+1F1F5"},"Costa Rica":{"flag":"🇨🇷","name":"Costa Rica","hex":"U+1F1E8 U+1F1F7"},"Cuba":{"flag":"🇨🇺","name":"Cuba","hex":"U+1F1E8 U+1F1FA"},"Cape Verde":{"flag":"🇨🇻","name":"Cape Verde","hex":"U+1F1E8 U+1F1FB"},"Curaçao":{"flag":"🇨🇼","name":"Curaçao","hex":"U+1F1E8 U+1F1FC"},"Christmas Island":{"flag":"🇨🇽","name":"Christmas Island","hex":"U+1F1E8 U+1F1FD"},"Cyprus":{"flag":"🇨🇾","name":"Cyprus","hex":"U+1F1E8 U+1F1FE"},"Czechia":{"flag":"🇨🇿","name":"Czechia","hex":"U+1F1E8 U+1F1FF"},"Germany":{"flag":"🇩🇪","name":"Germany","hex":"U+1F1E9 U+1F1EA"},"Diego Garcia":{"flag":"🇩🇬","name":"Diego Garcia","hex":"U+1F1E9 U+1F1EC"},"Djibouti":{"flag":"🇩🇯","name":"Djibouti","hex":"U+1F1E9 U+1F1EF"},"Denmark":{"flag":"🇩🇰","name":"Denmark","hex":"U+1F1E9 U+1F1F0"},"Dominica":{"flag":"🇩🇲","name":"Dominica","hex":"U+1F1E9 U+1F1F2"},"Dominican Republic":{"flag":"🇩🇴","name":"Dominican Republic","hex":"U+1F1E9 U+1F1F4"},"Algeria":{"flag":"🇩🇿","name":"Algeria","hex":"U+1F1E9 U+1F1FF"},"Ceuta & Melilla":{"flag":"🇪🇦","name":"Ceuta & Melilla","hex":"U+1F1EA U+1F1E6"},"Ecuador":{"flag":"🇪🇨","name":"Ecuador","hex":"U+1F1EA U+1F1E8"},"Estonia":{"flag":"🇪🇪","name":"Estonia","hex":"U+1F1EA U+1F1EA"},"Egypt":{"flag":"🇪🇬","name":"Egypt","hex":"U+1F1EA U+1F1EC"},"Western Sahara":{"flag":"🇪🇭","name":"Western Sahara","hex":"U+1F1EA U+1F1ED"},"Eritrea":{"flag":"🇪🇷","name":"Eritrea","hex":"U+1F1EA U+1F1F7"},"Spain":{"flag":"🇪🇸","name":"Spain","hex":"U+1F1EA U+1F1F8"},"Ethiopia":{"flag":"🇪🇹","name":"Ethiopia","hex":"U+1F1EA U+1F1F9"},"European Union":{"flag":"🇪🇺","name":"European Union","hex":"U+1F1EA U+1F1FA"},"Finland":{"flag":"🇫🇮","name":"Finland","hex":"U+1F1EB U+1F1EE"},"Fiji":{"flag":"🇫🇯","name":"Fiji","hex":"U+1F1EB U+1F1EF"},"Falkland Islands":{"flag":"🇫🇰","name":"Falkland Islands","hex":"U+1F1EB U+1F1F0"},"Micronesia":{"flag":"🇫🇲","name":"Micronesia","hex":"U+1F1EB U+1F1F2"},"Faroe Islands":{"flag":"🇫🇴","name":"Faroe Islands","hex":"U+1F1EB U+1F1F4"},"France":{"flag":"🇫🇷","name":"France","hex":"U+1F1EB U+1F1F7"},"Gabon":{"flag":"🇬🇦","name":"Gabon","hex":"U+1F1EC U+1F1E6"},"United Kingdom":{"flag":"🇬🇧","name":"United Kingdom","hex":"U+1F1EC U+1F1E7"},"Grenada":{"flag":"🇬🇩","name":"Grenada","hex":"U+1F1EC U+1F1E9"},"Georgia":{"flag":"🇬🇪","name":"Georgia","hex":"U+1F1EC U+1F1EA"},"French Guiana":{"flag":"🇬🇫","name":"French Guiana","hex":"U+1F1EC U+1F1EB"},"Guernsey":{"flag":"🇬🇬","name":"Guernsey","hex":"U+1F1EC U+1F1EC"},"Ghana":{"flag":"🇬🇭","name":"Ghana","hex":"U+1F1EC U+1F1ED"},"Gibraltar":{"flag":"🇬🇮","name":"Gibraltar","hex":"U+1F1EC U+1F1EE"},"Greenland":{"flag":"🇬🇱","name":"Greenland","hex":"U+1F1EC U+1F1F1"},"Gambia":{"flag":"🇬🇲","name":"Gambia","hex":"U+1F1EC U+1F1F2"},"Guinea":{"flag":"🇬🇳","name":"Guinea","hex":"U+1F1EC U+1F1F3"},"Guadeloupe":{"flag":"🇬🇵","name":"Guadeloupe","hex":"U+1F1EC U+1F1F5"},"Equatorial Guinea":{"flag":"🇬🇶","name":"Equatorial Guinea","hex":"U+1F1EC U+1F1F6"},"Greece":{"flag":"🇬🇷","name":"Greece","hex":"U+1F1EC U+1F1F7"},"South Georgia & South Sandwich Islands":{"flag":"🇬🇸","name":"South Georgia & South Sandwich Islands","hex":"U+1F1EC U+1F1F8"},"Guatemala":{"flag":"🇬🇹","name":"Guatemala","hex":"U+1F1EC U+1F1F9"},"Guam":{"flag":"🇬🇺","name":"Guam","hex":"U+1F1EC U+1F1FA"},"Guinea-Bissau":{"flag":"🇬🇼","name":"Guinea-Bissau","hex":"U+1F1EC U+1F1FC"},"Guyana":{"flag":"🇬🇾","name":"Guyana","hex":"U+1F1EC U+1F1FE"},"Hong Kong SAR China":{"flag":"🇭🇰","name":"Hong Kong SAR China","hex":"U+1F1ED U+1F1F0"},"Heard & McDonald Islands":{"flag":"🇭🇲","name":"Heard & McDonald Islands","hex":"U+1F1ED U+1F1F2"},"Honduras":{"flag":"🇭🇳","name":"Honduras","hex":"U+1F1ED U+1F1F3"},"Croatia":{"flag":"🇭🇷","name":"Croatia","hex":"U+1F1ED U+1F1F7"},"Haiti":{"flag":"🇭🇹","name":"Haiti","hex":"U+1F1ED U+1F1F9"},"Hungary":{"flag":"🇭🇺","name":"Hungary","hex":"U+1F1ED U+1F1FA"},"Canary Islands":{"flag":"🇮🇨","name":"Canary Islands","hex":"U+1F1EE U+1F1E8"},"Indonesia":{"flag":"🇮🇩","name":"Indonesia","hex":"U+1F1EE U+1F1E9"},"Ireland":{"flag":"🇮🇪","name":"Ireland","hex":"U+1F1EE U+1F1EA"},"Israel":{"flag":"🇮🇱","name":"Israel","hex":"U+1F1EE U+1F1F1"},"Isle of Man":{"flag":"🇮🇲","name":"Isle of Man","hex":"U+1F1EE U+1F1F2"},"India":{"flag":"🇮🇳","name":"India","hex":"U+1F1EE U+1F1F3"},"British Indian Ocean Territory":{"flag":"🇮🇴","name":"British Indian Ocean Territory","hex":"U+1F1EE U+1F1F4"},"Iraq":{"flag":"🇮🇶","name":"Iraq","hex":"U+1F1EE U+1F1F6"},"Iran":{"flag":"🇮🇷","name":"Iran","hex":"U+1F1EE U+1F1F7"},"Iceland":{"flag":"🇮🇸","name":"Iceland","hex":"U+1F1EE U+1F1F8"},"Italy":{"flag":"🇮🇹","name":"Italy","hex":"U+1F1EE U+1F1F9"},"Jersey":{"flag":"🇯🇪","name":"Jersey","hex":"U+1F1EF U+1F1EA"},"Jamaica":{"flag":"🇯🇲","name":"Jamaica","hex":"U+1F1EF U+1F1F2"},"Jordan":{"flag":"🇯🇴","name":"Jordan","hex":"U+1F1EF U+1F1F4"},"Japan":{"flag":"🇯🇵","name":"Japan","hex":"U+1F1EF U+1F1F5"},"Kenya":{"flag":"🇰🇪","name":"Kenya","hex":"U+1F1F0 U+1F1EA"},"Kyrgyzstan":{"flag":"🇰🇬","name":"Kyrgyzstan","hex":"U+1F1F0 U+1F1EC"},"Cambodia":{"flag":"🇰🇭","name":"Cambodia","hex":"U+1F1F0 U+1F1ED"},"Kiribati":{"flag":"🇰🇮","name":"Kiribati","hex":"U+1F1F0 U+1F1EE"},"Comoros":{"flag":"🇰🇲","name":"Comoros","hex":"U+1F1F0 U+1F1F2"},"St. Kitts & Nevis":{"flag":"🇰🇳","name":"St. Kitts & Nevis","hex":"U+1F1F0 U+1F1F3"},"North Korea":{"flag":"🇰🇵","name":"North Korea","hex":"U+1F1F0 U+1F1F5"},"South Korea":{"flag":"🇰🇷","name":"South Korea","hex":"U+1F1F0 U+1F1F7"},"Kuwait":{"flag":"🇰🇼","name":"Kuwait","hex":"U+1F1F0 U+1F1FC"},"Cayman Islands":{"flag":"🇰🇾","name":"Cayman Islands","hex":"U+1F1F0 U+1F1FE"},"Kazakhstan":{"flag":"🇰🇿","name":"Kazakhstan","hex":"U+1F1F0 U+1F1FF"},"Laos":{"flag":"🇱🇦","name":"Laos","hex":"U+1F1F1 U+1F1E6"},"Lebanon":{"flag":"🇱🇧","name":"Lebanon","hex":"U+1F1F1 U+1F1E7"},"St. Lucia":{"flag":"🇱🇨","name":"St. Lucia","hex":"U+1F1F1 U+1F1E8"},"Liechtenstein":{"flag":"🇱🇮","name":"Liechtenstein","hex":"U+1F1F1 U+1F1EE"},"Sri Lanka":{"flag":"🇱🇰","name":"Sri Lanka","hex":"U+1F1F1 U+1F1F0"},"Liberia":{"flag":"🇱🇷","name":"Liberia","hex":"U+1F1F1 U+1F1F7"},"Lesotho":{"flag":"🇱🇸","name":"Lesotho","hex":"U+1F1F1 U+1F1F8"},"Lithuania":{"flag":"🇱🇹","name":"Lithuania","hex":"U+1F1F1 U+1F1F9"},"Luxembourg":{"flag":"🇱🇺","name":"Luxembourg","hex":"U+1F1F1 U+1F1FA"},"Latvia":{"flag":"🇱🇻","name":"Latvia","hex":"U+1F1F1 U+1F1FB"},"Libya":{"flag":"🇱🇾","name":"Libya","hex":"U+1F1F1 U+1F1FE"},"Morocco":{"flag":"🇲🇦","name":"Morocco","hex":"U+1F1F2 U+1F1E6"},"Monaco":{"flag":"🇲🇨","name":"Monaco","hex":"U+1F1F2 U+1F1E8"},"Moldova":{"flag":"🇲🇩","name":"Moldova","hex":"U+1F1F2 U+1F1E9"},"Montenegro":{"flag":"🇲🇪","name":"Montenegro","hex":"U+1F1F2 U+1F1EA"},"St. Martin":{"flag":"🇲🇫","name":"St. Martin","hex":"U+1F1F2 U+1F1EB"},"Madagascar":{"flag":"🇲🇬","name":"Madagascar","hex":"U+1F1F2 U+1F1EC"},"Marshall Islands":{"flag":"🇲🇭","name":"Marshall Islands","hex":"U+1F1F2 U+1F1ED"},"Macedonia":{"flag":"🇲🇰","name":"Macedonia","hex":"U+1F1F2 U+1F1F0"},"Mali":{"flag":"🇲🇱","name":"Mali","hex":"U+1F1F2 U+1F1F1"},"Myanmar (Burma)":{"flag":"🇲🇲","name":"Myanmar (Burma)","hex":"U+1F1F2 U+1F1F2"},"Mongolia":{"flag":"🇲🇳","name":"Mongolia","hex":"U+1F1F2 U+1F1F3"},"Macao SAR China":{"flag":"🇲🇴","name":"Macao SAR China","hex":"U+1F1F2 U+1F1F4"},"Northern Mariana Islands":{"flag":"🇲🇵","name":"Northern Mariana Islands","hex":"U+1F1F2 U+1F1F5"},"Martinique":{"flag":"🇲🇶","name":"Martinique","hex":"U+1F1F2 U+1F1F6"},"Mauritania":{"flag":"🇲🇷","name":"Mauritania","hex":"U+1F1F2 U+1F1F7"},"Montserrat":{"flag":"🇲🇸","name":"Montserrat","hex":"U+1F1F2 U+1F1F8"},"Malta":{"flag":"🇲🇹","name":"Malta","hex":"U+1F1F2 U+1F1F9"},"Mauritius":{"flag":"🇲🇺","name":"Mauritius","hex":"U+1F1F2 U+1F1FA"},"Maldives":{"flag":"🇲🇻","name":"Maldives","hex":"U+1F1F2 U+1F1FB"},"Malawi":{"flag":"🇲🇼","name":"Malawi","hex":"U+1F1F2 U+1F1FC"},"Mexico":{"flag":"🇲🇽","name":"Mexico","hex":"U+1F1F2 U+1F1FD"},"Malaysia":{"flag":"🇲🇾","name":"Malaysia","hex":"U+1F1F2 U+1F1FE"},"Mozambique":{"flag":"🇲🇿","name":"Mozambique","hex":"U+1F1F2 U+1F1FF"},"Namibia":{"flag":"🇳🇦","name":"Namibia","hex":"U+1F1F3 U+1F1E6"},"New Caledonia":{"flag":"🇳🇨","name":"New Caledonia","hex":"U+1F1F3 U+1F1E8"},"Niger":{"flag":"🇳🇪","name":"Niger","hex":"U+1F1F3 U+1F1EA"},"Norfolk Island":{"flag":"🇳🇫","name":"Norfolk Island","hex":"U+1F1F3 U+1F1EB"},"Nigeria":{"flag":"🇳🇬","name":"Nigeria","hex":"U+1F1F3 U+1F1EC"},"Nicaragua":{"flag":"🇳🇮","name":"Nicaragua","hex":"U+1F1F3 U+1F1EE"},"Netherlands":{"flag":"🇳🇱","name":"Netherlands","hex":"U+1F1F3 U+1F1F1"},"Norway":{"flag":"🇳🇴","name":"Norway","hex":"U+1F1F3 U+1F1F4"},"Nepal":{"flag":"🇳🇵","name":"Nepal","hex":"U+1F1F3 U+1F1F5"},"Nauru":{"flag":"🇳🇷","name":"Nauru","hex":"U+1F1F3 U+1F1F7"},"Niue":{"flag":"🇳🇺","name":"Niue","hex":"U+1F1F3 U+1F1FA"},"New Zealand":{"flag":"🇳🇿","name":"New Zealand","hex":"U+1F1F3 U+1F1FF"},"Oman":{"flag":"🇴🇲","name":"Oman","hex":"U+1F1F4 U+1F1F2"},"Panama":{"flag":"🇵🇦","name":"Panama","hex":"U+1F1F5 U+1F1E6"},"Peru":{"flag":"🇵🇪","name":"Peru","hex":"U+1F1F5 U+1F1EA"},"French Polynesia":{"flag":"🇵🇫","name":"French Polynesia","hex":"U+1F1F5 U+1F1EB"},"Papua New Guinea":{"flag":"🇵🇬","name":"Papua New Guinea","hex":"U+1F1F5 U+1F1EC"},"Philippines":{"flag":"🇵🇭","name":"Philippines","hex":"U+1F1F5 U+1F1ED"},"Pakistan":{"flag":"🇵🇰","name":"Pakistan","hex":"U+1F1F5 U+1F1F0"},"Poland":{"flag":"🇵🇱","name":"Poland","hex":"U+1F1F5 U+1F1F1"},"St. Pierre & Miquelon":{"flag":"🇵🇲","name":"St. Pierre & Miquelon","hex":"U+1F1F5 U+1F1F2"},"Pitcairn Islands":{"flag":"🇵🇳","name":"Pitcairn Islands","hex":"U+1F1F5 U+1F1F3"},"Puerto Rico":{"flag":"🇵🇷","name":"Puerto Rico","hex":"U+1F1F5 U+1F1F7"},"Palestinian Territories":{"flag":"🇵🇸","name":"Palestinian Territories","hex":"U+1F1F5 U+1F1F8"},"Portugal":{"flag":"🇵🇹","name":"Portugal","hex":"U+1F1F5 U+1F1F9"},"Palau":{"flag":"🇵🇼","name":"Palau","hex":"U+1F1F5 U+1F1FC"},"Paraguay":{"flag":"🇵🇾","name":"Paraguay","hex":"U+1F1F5 U+1F1FE"},"Qatar":{"flag":"🇶🇦","name":"Qatar","hex":"U+1F1F6 U+1F1E6"},"Réunion":{"flag":"🇷🇪","name":"Réunion","hex":"U+1F1F7 U+1F1EA"},"Romania":{"flag":"🇷🇴","name":"Romania","hex":"U+1F1F7 U+1F1F4"},"Serbia":{"flag":"🇷🇸","name":"Serbia","hex":"U+1F1F7 U+1F1F8"},"Russia":{"flag":"🇷🇺","name":"Russia","hex":"U+1F1F7 U+1F1FA"},"Rwanda":{"flag":"🇷🇼","name":"Rwanda","hex":"U+1F1F7 U+1F1FC"},"Saudi Arabia":{"flag":"🇸🇦","name":"Saudi Arabia","hex":"U+1F1F8 U+1F1E6"},"Solomon Islands":{"flag":"🇸🇧","name":"Solomon Islands","hex":"U+1F1F8 U+1F1E7"},"Seychelles":{"flag":"🇸🇨","name":"Seychelles","hex":"U+1F1F8 U+1F1E8"},"Sudan":{"flag":"🇸🇩","name":"Sudan","hex":"U+1F1F8 U+1F1E9"},"Sweden":{"flag":"🇸🇪","name":"Sweden","hex":"U+1F1F8 U+1F1EA"},"Singapore":{"flag":"🇸🇬","name":"Singapore","hex":"U+1F1F8 U+1F1EC"},"St. Helena":{"flag":"🇸🇭","name":"St. Helena","hex":"U+1F1F8 U+1F1ED"},"Slovenia":{"flag":"🇸🇮","name":"Slovenia","hex":"U+1F1F8 U+1F1EE"},"Svalbard & Jan Mayen":{"flag":"🇸🇯","name":"Svalbard & Jan Mayen","hex":"U+1F1F8 U+1F1EF"},"Slovakia":{"flag":"🇸🇰","name":"Slovakia","hex":"U+1F1F8 U+1F1F0"},"Sierra Leone":{"flag":"🇸🇱","name":"Sierra Leone","hex":"U+1F1F8 U+1F1F1"},"San Marino":{"flag":"🇸🇲","name":"San Marino","hex":"U+1F1F8 U+1F1F2"},"Senegal":{"flag":"🇸🇳","name":"Senegal","hex":"U+1F1F8 U+1F1F3"},"Somalia":{"flag":"🇸🇴","name":"Somalia","hex":"U+1F1F8 U+1F1F4"},"Suriname":{"flag":"🇸🇷","name":"Suriname","hex":"U+1F1F8 U+1F1F7"},"South Sudan":{"flag":"🇸🇸","name":"South Sudan","hex":"U+1F1F8 U+1F1F8"},"São Tomé & Príncipe":{"flag":"🇸🇹","name":"São Tomé & Príncipe","hex":"U+1F1F8 U+1F1F9"},"El Salvador":{"flag":"🇸🇻","name":"El Salvador","hex":"U+1F1F8 U+1F1FB"},"Sint Maarten":{"flag":"🇸🇽","name":"Sint Maarten","hex":"U+1F1F8 U+1F1FD"},"Syria":{"flag":"🇸🇾","name":"Syria","hex":"U+1F1F8 U+1F1FE"},"Eswatini":{"flag":"🇸🇿","name":"Eswatini","hex":"U+1F1F8 U+1F1FF"},"Tristan da Cunha":{"flag":"🇹🇦","name":"Tristan da Cunha","hex":"U+1F1F9 U+1F1E6"},"Turks & Caicos Islands":{"flag":"🇹🇨","name":"Turks & Caicos Islands","hex":"U+1F1F9 U+1F1E8"},"Chad":{"flag":"🇹🇩","name":"Chad","hex":"U+1F1F9 U+1F1E9"},"French Southern Territories":{"flag":"🇹🇫","name":"French Southern Territories","hex":"U+1F1F9 U+1F1EB"},"Togo":{"flag":"🇹🇬","name":"Togo","hex":"U+1F1F9 U+1F1EC"},"Thailand":{"flag":"🇹🇭","name":"Thailand","hex":"U+1F1F9 U+1F1ED"},"Tajikistan":{"flag":"🇹🇯","name":"Tajikistan","hex":"U+1F1F9 U+1F1EF"},"Tokelau":{"flag":"🇹🇰","name":"Tokelau","hex":"U+1F1F9 U+1F1F0"},"Timor-Leste":{"flag":"🇹🇱","name":"Timor-Leste","hex":"U+1F1F9 U+1F1F1"},"Turkmenistan":{"flag":"🇹🇲","name":"Turkmenistan","hex":"U+1F1F9 U+1F1F2"},"Tunisia":{"flag":"🇹🇳","name":"Tunisia","hex":"U+1F1F9 U+1F1F3"},"Tonga":{"flag":"🇹🇴","name":"Tonga","hex":"U+1F1F9 U+1F1F4"},"Turkey":{"flag":"🇹🇷","name":"Turkey","hex":"U+1F1F9 U+1F1F7"},"Trinidad & Tobago":{"flag":"🇹🇹","name":"Trinidad & Tobago","hex":"U+1F1F9 U+1F1F9"},"Tuvalu":{"flag":"🇹🇻","name":"Tuvalu","hex":"U+1F1F9 U+1F1FB"},"Taiwan":{"flag":"🇹🇼","name":"Taiwan","hex":"U+1F1F9 U+1F1FC"},"Tanzania":{"flag":"🇹🇿","name":"Tanzania","hex":"U+1F1F9 U+1F1FF"},"Ukraine":{"flag":"🇺🇦","name":"Ukraine","hex":"U+1F1FA U+1F1E6"},"Uganda":{"flag":"🇺🇬","name":"Uganda","hex":"U+1F1FA U+1F1EC"},"U.S. Outlying Islands":{"flag":"🇺🇲","name":"U.S. Outlying Islands","hex":"U+1F1FA U+1F1F2"},"United Nations":{"flag":"🇺🇳","name":"United Nations","hex":"U+1F1FA U+1F1F3"},"United States":{"flag":"🇺🇸","name":"United States","hex":"U+1F1FA U+1F1F8"},"Uruguay":{"flag":"🇺🇾","name":"Uruguay","hex":"U+1F1FA U+1F1FE"},"Uzbekistan":{"flag":"🇺🇿","name":"Uzbekistan","hex":"U+1F1FA U+1F1FF"},"Vatican City":{"flag":"🇻🇦","name":"Vatican City","hex":"U+1F1FB U+1F1E6"},"St. Vincent & Grenadines":{"flag":"🇻🇨","name":"St. Vincent & Grenadines","hex":"U+1F1FB U+1F1E8"},"Venezuela":{"flag":"🇻🇪","name":"Venezuela","hex":"U+1F1FB U+1F1EA"},"British Virgin Islands":{"flag":"🇻🇬","name":"British Virgin Islands","hex":"U+1F1FB U+1F1EC"},"U.S. Virgin Islands":{"flag":"🇻🇮","name":"U.S. Virgin Islands","hex":"U+1F1FB U+1F1EE"},"Vietnam":{"flag":"🇻🇳","name":"Vietnam","hex":"U+1F1FB U+1F1F3"},"Vanuatu":{"flag":"🇻🇺","name":"Vanuatu","hex":"U+1F1FB U+1F1FA"},"Wallis & Futuna":{"flag":"🇼🇫","name":"Wallis & Futuna","hex":"U+1F1FC U+1F1EB"},"Samoa":{"flag":"🇼🇸","name":"Samoa","hex":"U+1F1FC U+1F1F8"},"Kosovo":{"flag":"🇽🇰","name":"Kosovo","hex":"U+1F1FD U+1F1F0"},"Yemen":{"flag":"🇾🇪","name":"Yemen","hex":"U+1F1FE U+1F1EA"},"Mayotte":{"flag":"🇾🇹","name":"Mayotte","hex":"U+1F1FE U+1F1F9"},"South Africa":{"flag":"🇿🇦","name":"South Africa","hex":"U+1F1FF U+1F1E6"},"Zambia":{"flag":"🇿🇲","name":"Zambia","hex":"U+1F1FF U+1F1F2"},"Zimbabwe":{"flag":"🇿🇼","name":"Zimbabwe","hex":"U+1F1FF U+1F1FC"},"England":{"flag":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","name":"England","hex":"U+1F3F4 U+E0067 U+E0062 U+E0065 U+E006E U+E0067 U+E007F"},"Scotland":{"flag":"🏴󠁧󠁢󠁳󠁣󠁴󠁿","name":"Scotland","hex":"U+1F3F4 U+E0067 U+E0062 U+E0073 U+E0063 U+E0074 U+E007F"},"Wales":{"flag":"🏴󠁧󠁢󠁷󠁬󠁳󠁿","name":"Wales","hex":"U+1F3F4 U+E0067 U+E0062 U+E0077 U+E006C U+E0073 U+E007F"}}

const countries = {

};

codes.forEach((code, i) => {
  countries[code?.toLocaleLowerCase()] = {
    code: code?.toLocaleLowerCase(),
    name: {
      en: en[i],
      fr: fr[i],
    },
    dial: dial[i],
    flag: flags[en[i]],
  };
});

console.log(countries);
